version: '3'
services:
  db:
    image: mariadb:10.11
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    restart: always
    volumes:
      - db:/var/lib/mysql
    env_file:
      - db.env

  redis:
    image: redis:alpine
    restart: always

  app:
    image: nextcloud:25.0.1-apache
    restart: always
    volumes:
      - nextcloud:/var/www/html
      - ./nextcloud-data:/var/www/html/data
      - ./nextcloud/config.ini:/usr/local/etc/php/conf.d/config.php
    ports:
      - 80:80
    environment:
      - MYSQL_HOST=db
      - REDIS_HOST=redis
      - PHP_UPLOAD_LIMIT=200G
      - PHP_MEMORY_LIMIT=8G
      - NEXTCLOUD_TRUSTED_DOMAINS="uploader.cloudnativedays.jp"
      - OVERWRITEPROTOCOL=https
      - OVERWRITECLIURL=https://uploader.cloudnativedays.jp
    env_file:
      - db.env
    depends_on:
      - db
      - redis
    networks:
      - default

volumes:
  db:
  nextcloud: