# coding: utf-8

"""
    Dreamkast API

    This is a API definition of the Dreamakst. You can find a documentation of this API at http://api-docs.dev.cloudnativedays.jp/.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""

from openapi_client.paths.api_v1_events_event_abbr.get import ApiV1EventsEventAbbrGet
from openapi_client.paths.api_v1_events.get import ApiV1EventsGet


class EventApi(
    ApiV1EventsEventAbbrGet,
    ApiV1EventsGet,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
